### ISSUE TITLE
Definição das APIs REST

### ISSUE THREAD

**Issue by jeffersonrpn** [joaoarthurbm/ciframe#2]
GET /similares?acordes='C,..,D'&generos='rock,samba,...'
GET /similares?id_musica=nome-artista_nome-musica
GET /similares?sequencias=CGAmF
GET /search?keyword=string&generos='rock,samba,pagode,....'
GET /genero

**Comment by joaoarthurbm** [comment]
Criei issues separadas para cada feature.
